directory: ~/media/music
plugins: fetchart scrub ftintitle parentwork fish inline
artist_credit: no
import:
  move: yes
  languages: en
musicbrainz: 
  genres: yes    
fetchart:
  sources: filesystems itunes amazon coverart albumart
parentwork:
  auto: yes
asciify_paths: yes
item_fields:
  myartist: albumartist.split(';')[0]
paths:
  default: $myartist/[$year] $album%aunique{}/$track $title
